"""added 'filename' and 'filepath' field to Post model

Revision ID: 5a936c028979
Revises: 8b976aaadf71
Create Date: 2024-08-10 12:03:14.905478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a936c028979'
down_revision = '8b976aaadf71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('filepath', sa.String(), nullable=True))
        batch_op.drop_column('img_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_name', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('filepath')
        batch_op.drop_column('filename')

    # ### end Alembic commands ###
