"""added 'post_image' field to Post model

Revision ID: 8b976aaadf71
Revises: 38ce4f5e3ae9
Create Date: 2024-08-09 17:05:49.734057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b976aaadf71'
down_revision = '38ce4f5e3ae9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_image', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('post_image')

    # ### end Alembic commands ###
